 import type {NextPage} from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from "next/link";

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>My Dashboard</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to Dashboard!
                </h1>

                <br/>

                <h2>Articles <Link href={"/articles"}>More...</Link></h2>

                <br/>

            </main>

            <footer className={styles.footer}>
                <a href={"https://github.com/jinwoo1225"}>github.com/jinwoo1225</a>
            </footer>
        </div>
    )
}

export default Home
